### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by min0609** [CSB5/lofreq#140]
Hi,

First of all, thank you for this wonderful tool.
I attempted to run a command to call somatic variants, but unfortunately, the command failed. 
Could you please suggest a way to troubleshoot this error?

`~/palmer_scratch/km/tools/lofreq_star-2.1.5_linux-x86-64/bin/lofreq somatic -n ~/palmer_scratch/km/ova_low_coverage/sample_05-S02_B/sample_05-S02_B.bam -t ~/palmer_scratch/km/ova_low_coverage/sample_05-S02_P/sample_05-S02_P.bam -l ~/palmer_scratch/km/ova_wes/ref/SureSelect_Human_All_Exon_V5.bed -f ~/palmer_scratch/km/ova_wes/db/human_g1k_v37_decoy.fasta --threads 8 -o sample_05-S02_ -d ~/palmer_scratch/km/ova_wes/db/dbsnp_137.b37.vcf.gz`

CRITICAL [2023-10-18 06:49:50,574]: The following command failed with code 1: lofreq call-parallel --pp-threads 8 -d 101000 -f /home/jc2545/palmer_scratch/km/ova_wes/db/human_g1k_v37_decoy.fasta --verbose --no-default-filter -b 1 -l /home/jc2545/palmer_scratch/km/ova_wes/ref/SureSelect_Human_All_Exon_V5.bed -a 0.100000 --use-orphan -B -N -A /home/jc2545/palmer_scratch/km/ova_low_coverage/sample_05-S02_B/sample_05-S02_B.bam -o sample_05-S02_normal_relaxed.vcf.gz
CRITICAL [2023-10-18 06:49:50,574]: Received the following on stderr:
INFO [2023-10-18 06:49:49,659]: Using 8 threads with following basic args: lofreq call -d 101000 -f /home/jc2545/palmer_scratch/km/ova_wes/db/human_g1k_v37_decoy.fasta --verbose --no-default-filter -b 1 -a 0.100000 --use-orphan -B -N -A /home/jc2545/palmer_scratch/km/ova_low_coverage/sample_05-S02_B/sample_05-S02_B.bam

Traceback (most recent call last):

  File "/vast/palmer/scratch/lifton/jc2545/km/tools/lofreq_star-2.1.5_linux-x86-64/bin/lofreq2_call_pparallel.py", line 744, in <module>

    main()

  File "/vast/palmer/scratch/lifton/jc2545/km/tools/lofreq_star-2.1.5_linux-x86-64/bin/lofreq2_call_pparallel.py", line 593, in main

    biggest = bins[-1]

IndexError: list index out of range

CRITICAL [2023-10-18 06:49:50,574]: Somatic SNV caller failed. Exiting

**Comment by andreas-wilm** [comment]
Could you please post the first two lines of the bed file here?

**Comment by min0609** [comment]
Here are the first ten lines of the bed file.

chr1	65509	65625	-
chr1	65831	65973	-
chr1	69481	69600	OR4F5
chr1	721381	721519	ENST00000591440
chr1	721530	721806	ENST00000591440
chr1	721851	721942	ENST00000591
chr1	752916	753035	FAM87B
chr1	762095	762275	LINC00115
chr1	762280	762414	LINC00115
chr1	762420	762565	LINC00115

**Comment by andreas-wilm** [comment]
Hm. What does `file ~/palmer_scratch/km/ova_wes/ref/SureSelect_Human_All_Exon_V5.bed` return?

And could you also please share the output of `samtools view -H /home/jc2545/palmer_scratch/km/ova_low_coverage/sample_05-S02_B/sample_05-S02_B.bam`

Thanks

**Comment by min0609** [comment]
These are the outputs of the commands.

/home/jc2545/palmer_scratch/km/ova_wes/ref/SureSelect_Human_All_Exon_V5.bed: ASCII text

[samtools_view_H.txt](https://github.com/CSB5/lofreq/files/13026157/samtools_view_H.txt)

The SureSelect_Human_All_Exon_V5.bed file was not used in GATK. Did this cause the error?

Thank you!

**Comment by andreas-wilm** [comment]
Unlikely. This all looks fine and I never came across this problem. If you could also share the full bed file then I can start debugging

**Comment by min0609** [comment]
[SureSelect_Human_All_Exon_V5.txt](https://github.com/CSB5/lofreq/files/13029623/SureSelect_Human_All_Exon_V5.txt)

This is the BED file, and I converted it to a TXT format because BED format is not supported here.

**Comment by andreas-wilm** [comment]
Thanks. I still can't see anything unusual. Could you please just run the failing `lofreq call` command with `lofreq call --verbose --debug -d 101000 -f /home/jc2545/palmer_scratch/km/ova_wes/db/human_g1k_v37_decoy.fasta --verbose --no-default-filter -b 1 -a 0.100000 --use-orphan -B -N -A /home/jc2545/palmer_scratch/km/ova_low_coverage/sample_05-S02_B/sample_05-S02_B.bam` (with the added `--debug` flag) and share the output here?
