### ISSUE TITLE
lofreq2_add_fake_gt.py python 3 support

### ISSUE THREAD

**Issue by igordot** [CSB5/lofreq#75]
From a previous issue (https://github.com/CSB5/lofreq/issues/53), I found out about the `lofreq2_add_fake_gt.py` script for adding a fake sample column. According to the changelog, LoFreq 2.1.3 added support for Python 3. However, `lofreq2_add_fake_gt.py` gives me an error with Python 3 (it works with Python 2):
```
Traceback (most recent call last):
  File "/path/lofreq2_add_fake_gt.py", line 184, in <module>
    main()
  File "/path/lofreq2_add_fake_gt.py", line 179, in main
    add_fake_gt(args.vcf_in, args.vcf_out, args.samples)
  File "/path/lofreq2_add_fake_gt.py", line 140, in add_fake_gt
    vcf_writer.writerow(row)
TypeError: a bytes-like object is required, not 'str'
```

**Comment by romunov** [comment]
My guess would be that strings should be converted to byte-strings before being written. Just to make sure, can you provide a small portion of your vcf file to verify this?

**Comment by igordot** [comment]
Here is part of a VCF:

```
##fileformat=VCFv4.0
##fileDate=20190215
##source=lofreq call --call-indels --ref /path/ref/hg19/genome.fa --no-default-filter -r chr1:27022885-27024041 -o /tmp/lofreq2_call_parallelWczIM5/0.vcf.gz /path/3T.bam 
##reference=/path/ref/hg19/genome.fa
##INFO=<ID=DP,Number=1,Type=Integer,Description="Raw Depth">
##INFO=<ID=AF,Number=1,Type=Float,Description="Allele Frequency">
##INFO=<ID=SB,Number=1,Type=Integer,Description="Phred-scaled strand bias at this position">
##INFO=<ID=DP4,Number=4,Type=Integer,Description="Counts for ref-forward bases, ref-reverse, alt-forward and alt-reverse bases">
##INFO=<ID=INDEL,Number=0,Type=Flag,Description="Indicates that the variant is an INDEL.">
##INFO=<ID=CONSVAR,Number=0,Type=Flag,Description="Indicates that the variant is a consensus variant (as opposed to a low frequency variant).">
##INFO=<ID=HRUN,Number=1,Type=Integer,Description="Homopolymer length to the right of report indel position">
##FILTER=<ID=min_snvqual_50,Description="Minimum SNV Quality (Phred) 50">
##FILTER=<ID=min_indelqual_34,Description="Minimum Indel Quality (Phred) 34">
##FILTER=<ID=min_dp_10,Description="Minimum Coverage 10">
##FILTER=<ID=sb_fdr,Description="Strand-Bias Multiple Testing Correction: fdr corr. pvalue > 0.001000">
##FILTER=<ID=min_snvqual_68,Description="Minimum SNV Quality (Phred) 68">
##FILTER=<ID=min_indelqual_50,Description="Minimum Indel Quality (Phred) 50">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO
chr1	27022939	.	CCCG	C	579	PASS	DP=591;AF=0.040609;SB=0;DP4=309,255,13,11;INDEL;HRUN=3
chr1	27022939	.	CCCGCCG	C	50	PASS	DP=591;AF=0.005076;SB=10;DP4=309,255,0,3;INDEL;HRUN=3
chr1	27023007	.	AGGC	A	183	PASS	DP=623;AF=0.014446;SB=4;DP4=313,304,3,6;INDEL;HRUN=2
chr1	27023140	.	TGGC	T	177	PASS	DP=655;AF=0.013740;SB=2;DP4=319,329,3,6;INDEL;HRUN=2
chr3	49412996	.	C	T	1295	PASS	DP=124;AF=0.411290;SB=2;DP4=31,42,19,32
chr3	53529192	.	GGAT	G	84	PASS	DP=246;AF=0.020325;SB=0;DP4=149,90,3,2;INDEL;HRUN=2
chr3	53531494	.	CT	C	151	PASS	DP=375;AF=0.018667;SB=0;DP4=120,248,2,5;INDEL;HRUN=7
chr3	53700373	.	A	G	3706	PASS	DP=358;AF=0.413408;SB=0;DP4=124,86,88,60
chr3	53700550	.	T	C	9079	PASS	DP=279;AF=0.996416;SB=0;DP4=0,0,87,191
chr3	53804483	.	CT	C	79	PASS	DP=391;AF=0.010230;SB=0;DP4=202,187,2,2;INDEL;HRUN=5
chr3	53845295	.	C	T	10716	PASS	DP=342;AF=0.994152;SB=0;DP4=1,1,156,184
chr3	71026157	.	T	TC	69	PASS	DP=340;AF=0.008824;SB=2;DP4=144,196,2,1;INDEL;HRUN=3
chr3	71102804	.	CCTG	C	71	PASS	DP=698;AF=0.005731;SB=0;DP4=374,325,2,2;INDEL;HRUN=2
chr3	71247373	.	C	CT	89	PASS	DP=494;AF=0.008097;SB=0;DP4=263,229,2,2;INDEL;HRUN=1
chr4	153268227	.	CA	C	319	PASS	DP=162;AF=0.092593;SB=1;DP4=37,98,3,12;INDEL;HRUN=14
chr4	153268227	.	CAAA	C	130	PASS	DP=162;AF=0.037037;SB=12;DP4=37,98,4,2;INDEL;HRUN=14
chr4	153268227	.	CAA	C	81	PASS	DP=162;AF=0.024691;SB=0;DP4=37,98,1,3;INDEL;HRUN=14
chr4	153268227	.	C	A	170	PASS	DP=162;AF=0.160494;SB=41;DP4=46,83,0,26
chr4	153332604	.	TCTC	T	132	PASS	DP=346;AF=0.017341;SB=0;DP4=171,172,3,3;INDEL;HRUN=1
chr5	56111402	.	TGGC	T	123	PASS	DP=511;AF=0.013699;SB=1;DP4=322,185,4,3;INDEL;HRUN=2
chr5	56111445	.	G	A	4156	PASS	DP=548;AF=0.321168;SB=0;DP4=210,162,100,76
chr5	56111565	.	G	A	3622	PASS	DP=489;AF=0.312883;SB=0;DP4=139,197,63,90
chr5	56111751	.	G	C	10073	PASS	DP=539;AF=0.649351;SB=3;DP4=93,96,185,165
chr5	56161787	.	G	A	5312	PASS	DP=170;AF=1.000000;SB=0;DP4=0,0,46,124
```

**Comment by andreas-wilm** [comment]
Hey @igordot, sorry for the radio silence. I've tested the script on one of my and also your vcf file and it works just fine with the 3.7 interpreter I have installed. What does `$(which python) -V` return for you?
